export enum ActionTypes {
  UPDATE_ARTICLE = '[UPDATE ARTICLE] UPDATE Articles',
  UPDATE_ARTICLE_SUCCESS = '[UPDATE ARTICLE] UPDATE Articles success',
  UPDATE_ARTICLE_FAILURE = '[UPDATE ARTICLE] UPDATE Articles failure',

  GET_ARTICLE = '[GET ARTICLE] GET Articles',
  GET_ARTICLE_SUCCESS = '[GET ARTICLE] GET Articles success',
  GET_ARTICLE_FAILURE = '[GET ARTICLE] GET Articles failure',
}
